import { describe, expect, test } from "bun:test";
import { promises as fs } from "node:fs";
import path from "node:path";
import { tmpdir } from "node:os";
import { build } from "../src/build";
import { CACHE_VERSION } from "../src/cache";

// deterministic large-repo fixture (generated by scripts/gen-fixture.ts,
// exercised here without any live download). Copied to a unique dir per run
// with an isolated cache so edits never poison shared state.
const SRC = path.join(import.meta.dir, "..", "var", "large-fixture", "small-7");

async function freshFixture(): Promise<{ root: string; cleanup: () => Promise<void> }> {
  const root = path.join(tmpdir(), "ctx-fixture-" + Date.now() + "-" + Math.random().toString(36).slice(2));
  const cache = path.join(tmpdir(), "ctx-fixture-cache-" + Date.now() + "-" + Math.random().toString(36).slice(2));
  await fs.cp(SRC, root, { recursive: true });
  const prev = process.env.XDG_CACHE_HOME;
  process.env.XDG_CACHE_HOME = cache;
  return {
    root,
    cleanup: async () => {
      if (prev === undefined) delete process.env.XDG_CACHE_HOME;
      else process.env.XDG_CACHE_HOME = prev;
      await fs.rm(root, { recursive: true, force: true });
      await fs.rm(cache, { recursive: true, force: true });
    },
  };
}

describe("large-repo incremental correctness", () => {
  test("fixture exists (generated by scripts/gen-fixture.ts)", async () => {
    try {
      await fs.access(path.join(SRC, "manifest.json"));
      expect(true).toBe(true);
    } catch {
      throw new Error(`run 'bun run scripts/gen-fixture.ts' first (missing ${SRC})`);
    }
  });

  test("cold parses, warm reuses everything", async () => {
    const f = await freshFixture();
    try {
      const cold = await build(f.root);
      expect(cold.parsed).toBeGreaterThan(100);
      expect(cold.docs.length).toBeGreaterThan(50);
      expect(cold.docs.every((d) => d.sections.length > 0)).toBe(true);

      const warm = await build(f.root);
      expect(warm.parsed).toBe(0);
      expect(warm.reused).toBeGreaterThanOrEqual(cold.parsed);
      // content identity: unchanged docs are byte-for-byte identical
      expect(warm.docs.map((d) => d.hash).sort()).toEqual(cold.docs.map((d) => d.hash).sort());
      expect(warm.cacheBytes).toBeGreaterThan(0);
    } finally {
      await f.cleanup();
    }
  });

  test("one code edit reparses exactly that file", async () => {
    const f = await freshFixture();
    try {
      const cold = await build(f.root);
      const target = path.join(f.root, "code", "m3.go");
      await fs.appendFile(target, "\n// touch\n");
      const next = await build(f.root);
      expect(next.parsed).toBe(1);
      expect(next.changed.has("code/m3.go")).toBe(true);
      expect(next.reused).toBe(cold.parsed - 1);
      const m3 = next.fileFacts.get("code/m3.go");
      expect(m3).toBeDefined();
    } finally {
      await f.cleanup();
    }
  });

  test("same-size + restored-mtime doc edit is detected (content identity)", async () => {
    const f = await freshFixture();
    try {
      const cold = await build(f.root);
      const docFile = path.join(f.root, "docs", "m7.md");
      const old = await fs.readFile(docFile, "utf8");
      const oldStat = await fs.stat(docFile);
      const oldHash = cold.docs.find((d) => d.file === "docs/m7.md")!.hash;

      // same byte length, different content, mtime restored to the original
      const swapped = old.replace("sentence 0", "sentence 1").replace("defaults.", "defaults!");
      expect(Buffer.byteLength(swapped, "utf8")).toBe(Buffer.byteLength(old, "utf8"));
      await fs.writeFile(docFile, swapped);
      await fs.utimes(docFile, oldStat.atime, oldStat.mtime);

      const next = await build(f.root);
      const newHash = next.docs.find((d) => d.file === "docs/m7.md")!.hash;
      expect(newHash).not.toBe(oldHash);
    } finally {
      await f.cleanup();
    }
  });
});

describe("cache schema", () => {
  test("extraction/section schema is versioned", () => {
    expect(CACHE_VERSION).toMatch(/^context-cache-v\d+$/);
  });
});
